# Generated by Django 5.1.1 on 2024-09-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_2011', '0002_alter_pollingunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollingunit',
            options={'managed': False},
        ),
    ]
